-- Create "tenants" table
CREATE TABLE "tenants" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "type" character varying NOT NULL DEFAULT 'platform',
  "status" character varying NOT NULL DEFAULT 'draft',
  "brand_name" character varying NULL,
  "domain" character varying NULL,
  "parent_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "tenants_tenants_children" FOREIGN KEY ("parent_id") REFERENCES "tenants" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "tenants_brand_name_key" to table: "tenants"
CREATE UNIQUE INDEX "tenants_brand_name_key" ON "tenants" ("brand_name");
-- Create index "tenants_domain_key" to table: "tenants"
CREATE UNIQUE INDEX "tenants_domain_key" ON "tenants" ("domain");
-- Create index "tenants_name_key" to table: "tenants"
CREATE UNIQUE INDEX "tenants_name_key" ON "tenants" ("name");
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "first_name" character varying(50) NOT NULL,
  "last_name" character varying NOT NULL,
  "mobile" character varying NOT NULL,
  "email" character varying NOT NULL,
  "password_hash" character varying NOT NULL,
  "status" boolean NOT NULL,
  "status2" boolean NOT NULL,
  "status3" boolean NOT NULL,
  "tenant_users" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "users_tenants_users" FOREIGN KEY ("tenant_users") REFERENCES "tenants" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
