-- Create "permissions" table
CREATE TABLE "permissions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id")
);
-- Create "roles" table
CREATE TABLE "roles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id")
);
-- Create "scopes" table
CREATE TABLE "scopes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id")
);
