// Code generated by ent, DO NOT EDIT.

package ent

import (
	"message-platform/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
}
