// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"message-platform/ent/predicate"
	"message-platform/ent/tenant"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *TenantUpdate) SetParentID(v int) *TenantUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableParentID(v *int) *TenantUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *TenantUpdate) AddParentID(v int) *TenantUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v []string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// AppendName appends value to the "name" field.
func (_u *TenantUpdate) AppendName(v []string) *TenantUpdate {
	_u.mutation.AppendName(v)
	return _u
}

// SetType sets the "type" field.
func (_u *TenantUpdate) SetType(v []string) *TenantUpdate {
	_u.mutation.SetType(v)
	return _u
}

// AppendType appends value to the "type" field.
func (_u *TenantUpdate) AppendType(v []string) *TenantUpdate {
	_u.mutation.AppendType(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdate) SetStatus(v []string) *TenantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// AppendStatus appends value to the "status" field.
func (_u *TenantUpdate) AppendStatus(v []string) *TenantUpdate {
	_u.mutation.AppendStatus(v)
	return _u
}

// SetBrandName sets the "brand_name" field.
func (_u *TenantUpdate) SetBrandName(v []string) *TenantUpdate {
	_u.mutation.SetBrandName(v)
	return _u
}

// AppendBrandName appends value to the "brand_name" field.
func (_u *TenantUpdate) AppendBrandName(v []string) *TenantUpdate {
	_u.mutation.AppendBrandName(v)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdate) SetDomain(v []string) *TenantUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// AppendDomain appends value to the "domain" field.
func (_u *TenantUpdate) AppendDomain(v []string) *TenantUpdate {
	_u.mutation.AppendDomain(v)
	return _u
}

// SetDomain3 sets the "domain3" field.
func (_u *TenantUpdate) SetDomain3(v []string) *TenantUpdate {
	_u.mutation.SetDomain3(v)
	return _u
}

// AppendDomain3 appends value to the "domain3" field.
func (_u *TenantUpdate) AppendDomain3(v []string) *TenantUpdate {
	_u.mutation.AppendDomain3(v)
	return _u
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(tenant.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(tenant.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedName(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldName, value)
		})
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(tenant.FieldType, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedType(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldType, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedStatus(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldStatus, value)
		})
	}
	if value, ok := _u.mutation.BrandName(); ok {
		_spec.SetField(tenant.FieldBrandName, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBrandName(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldBrandName, value)
		})
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDomain(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldDomain, value)
		})
	}
	if value, ok := _u.mutation.Domain3(); ok {
		_spec.SetField(tenant.FieldDomain3, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDomain3(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldDomain3, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetParentID sets the "parent_id" field.
func (_u *TenantUpdateOne) SetParentID(v int) *TenantUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableParentID(v *int) *TenantUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *TenantUpdateOne) AddParentID(v int) *TenantUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v []string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// AppendName appends value to the "name" field.
func (_u *TenantUpdateOne) AppendName(v []string) *TenantUpdateOne {
	_u.mutation.AppendName(v)
	return _u
}

// SetType sets the "type" field.
func (_u *TenantUpdateOne) SetType(v []string) *TenantUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// AppendType appends value to the "type" field.
func (_u *TenantUpdateOne) AppendType(v []string) *TenantUpdateOne {
	_u.mutation.AppendType(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdateOne) SetStatus(v []string) *TenantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// AppendStatus appends value to the "status" field.
func (_u *TenantUpdateOne) AppendStatus(v []string) *TenantUpdateOne {
	_u.mutation.AppendStatus(v)
	return _u
}

// SetBrandName sets the "brand_name" field.
func (_u *TenantUpdateOne) SetBrandName(v []string) *TenantUpdateOne {
	_u.mutation.SetBrandName(v)
	return _u
}

// AppendBrandName appends value to the "brand_name" field.
func (_u *TenantUpdateOne) AppendBrandName(v []string) *TenantUpdateOne {
	_u.mutation.AppendBrandName(v)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdateOne) SetDomain(v []string) *TenantUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// AppendDomain appends value to the "domain" field.
func (_u *TenantUpdateOne) AppendDomain(v []string) *TenantUpdateOne {
	_u.mutation.AppendDomain(v)
	return _u
}

// SetDomain3 sets the "domain3" field.
func (_u *TenantUpdateOne) SetDomain3(v []string) *TenantUpdateOne {
	_u.mutation.SetDomain3(v)
	return _u
}

// AppendDomain3 appends value to the "domain3" field.
func (_u *TenantUpdateOne) AppendDomain3(v []string) *TenantUpdateOne {
	_u.mutation.AppendDomain3(v)
	return _u
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(tenant.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(tenant.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedName(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldName, value)
		})
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(tenant.FieldType, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedType(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldType, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedStatus(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldStatus, value)
		})
	}
	if value, ok := _u.mutation.BrandName(); ok {
		_spec.SetField(tenant.FieldBrandName, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBrandName(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldBrandName, value)
		})
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDomain(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldDomain, value)
		})
	}
	if value, ok := _u.mutation.Domain3(); ok {
		_spec.SetField(tenant.FieldDomain3, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDomain3(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldDomain3, value)
		})
	}
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
